### ISSUE TITLE
Response-Headers are stripped but needed

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#118]
When creating a NextcloudRequest (without Retrofit, but putting the request together manually) i do not get the Server response headers.

I urgently need them for proper caching (Etags and Modified header e.g.)

cc @David-Development

**Comment by stefan-niedermann** [comment]
As i stated in our chat, receiving respinse headers might also be needed in the future for features like caching images properly (where the caching-informations can not simply be added to the json response).

There might be even more use-cases which are not visible at the moment.

The idea of capsulating HTTP is okay, but there definitely has to be a way of at least optionally access the headers to use the benefits like SSO, Certificate-Management, the Account-Picker (...) while still being able to access the response-headers (*even* if this means a breaking change for the SSO IMHO).

One idea that came up from @tobiasKaminsky was to wrap the InputStream of the response in a wrapper object which also holds the response headers.

**Comment by tobiasKaminsky** [comment]
Here is my current progress:

Android: https://github.com/nextcloud/android/pull/4725
Notes: https://github.com/stefan-niedermann/nextcloud-notes/pull/610
SSO: https://github.com/nextcloud/Android-SingleSignOn/pull/128

**Comment by stefan-niedermann** [comment]
Guess this can be closed?
