### ISSUE TITLE
Adding a new account from 3rd-party-app does not return to 3rd-party app

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#119]
Given you have configured Account A in files app.

Now open Notes or another 3rd-Party-app and trigger pickAccount-dialog. Instead of choosing Account A, click "Add account" and add completely new Account B.

Current behavior: Account B gets imported, but user gets redirected to files app

Expected behavior: Account B gets added and redirected back to the requesting 3rd-Party-app

**Comment by tobiasKaminsky** [comment]
Hm. I even fail to find where the "add account" is set, as somewhere this must be set to our files app, or is this something automatically by Android?

You pass activity to AccountImporter.pickNewAccount(…), so I would have expected that you then also get redirect to this activity once the intent is done.
Do you have onActivityResult(…) implemented on your side?

**Comment by stefan-niedermann** [comment]
Try deck app, (notes is on an experimental branch).

Yes, i pass the activity and i have implemented onActivityResult, but this works only when selecting an account which is already configured in the files app, but not when you choose "add account"

**Comment by David-Development** [comment]
@tobiasKaminsky It's the same as if you go to your phone settings --> accounts --> add new account --> nextcloud. 
Which activity is actually called is defined in your `AbstractAccountAuthenticator`

See: https://github.com/nextcloud/android/blob/03e04e516efd31077cd3d2c3ad18387d22f5daf9/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java#L77

**Comment by tobiasKaminsky** [comment]
Hm. But then I have no idea how to do this…
AccountManager.newChooseAccountIntent…) also has no parameter to allow this.
Maybe it is not even possible?

**Comment by stefan-niedermann** [comment]
Retested with `3.16.0` and behavior is as expected now.
