### ISSUE TITLE
Keep or recreate NextcloudAPI instance?

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#120]
Is it recommended to keep the instance of `NextcloudAPI` alive as long as possible or should one create the instance at each request from scratch (and call `.stop()` it after the response has arrived)?

**Comment by David-Development** [comment]
If you need to make multiple calls, keep it open as long as you can. This way the services will stay active and the connection between the files app and your app is already established when you make subsequent requests. Otherwise you'll have to bind to the service again and again for each request.

**Comment by stefan-niedermann** [comment]
I think i have another question to this topic.

Currently i reinstantiate a new `NextcloudAPI` instance everytime i switch the my account in the Notes app: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesClient.java#L99

I tried to do this no longer in order to keep the instance as long alive as possible and it worked just fine. (Basically i deleted the whole `updateAccount()` stuff).

My conclusion: The `SingleSignOnAccount` object, which i pass to the `NextcloudAPI` does not limit my `NextcloudAPI` to requests for this account.

My questions:
- Is my conclusion correct? I can create `NextcloudAPI` with `SingleSignOnAccount` **A** and use it to make network calls to `SingleSignOnAccount` **B**?
- If yes: Why is the `SingleSignOnAccount` then even needed?

**Comment by stefan-niedermann** [comment]
Oh, seems i went wrong, no? I just checked it again, but it seems that if i do reinstantiate a new `NextcloudAPI`, then the requests to another accounts are failing...
