### ISSUE TITLE
How to authenticate single account by accountName?

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#121]
Given i have the raw String `user@nextcloud.example.com` in a 3rd-party-app *(and configured this account in the files app)* and i am in an `Activity`: How can i trigger the authentication for exactly this account?

I have tried `AccountImporter.authenticateSingleSignAccount(this);` and `AccountImporter.getAccountForName(this, "user@nextcloud.example.com");` so far, but none of the methods opens the expected android permission dialog. Instead i am always ending up with a `NextcloudFilesAppAccountNotFoundException`. And yes, i made sure, that the files app knows this account.

If i choose `AccountImporter.pickNewAccount(this)`, everything works expected and fine (and also the wanted account is in the list, of course) - except that i do not want to pick an account from a list but only grant access to this special account.

Am i using the lib wrong or is it even possible to use the lib this ways? Background: The Notes android app knows the usernames and hosts. I want to use this information to migrate smoothly to SingleSign-On (keeping all data and just authenticate the 3rd-party app as a now-client for the files-app).

**Comment by tobiasKaminsky** [comment]
As far as I remember you have to use pickNewAccount, as this is calling AccountManager.newChooseAccountIntent(…) which makes sure that user is granting the account (for Android), so that we can access the account.
The later "grand access" dialog is only for us and theoretically not needed, but better for good UX.

What you could try is to only pass the one desired account into pickNewAccount. Youl will then see the "add new account", I fear, as this is nothing we can control.

**Comment by stefan-niedermann** [comment]
How can i pass the desired account to `pickNewAccount`? It only accepts a single argument which has to be `Activity` or `Fragment`?

**Comment by tobiasKaminsky** [comment]
Try the new branch: https://github.com/nextcloud/Android-SingleSignOn/pull/108/files#diff-6ad158bec90aaf2023374e3b382771a2R90

**Comment by stefan-niedermann** [comment]
Aaah, got it. I fetch the `Account` via `AccountImporter.getAccountForName(accountName)` and pass the result into `AccountImporter.pickNewAccount(myActivity, listWithMyAccountEntry)`?

I will try this as soon as possible and give feedback whether or not it works :) Thank you.
