### ISSUE TITLE
Getting error when compile option is missing

### ISSUE THREAD

**Issue by Muehli25** [nextcloud/Android-SingleSignOn#122]
If in the build.gradle this part is not present 

```    
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
I got this error message.
Maybe add this to the README.md
```
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at com.nextcloud.android.sso.api.NetworkRequest.connectApiWithBackoff(NetworkRequest.java:40)
        at com.nextcloud.android.sso.api.NextcloudAPI$1.run(NextcloudAPI.java:73)
```

**Comment by David-Development** [comment]
@Muehli25 Thank you for your feedback!
Since we are using some features from Java 8 (such as Lambdas etc) we added these compile options to our `build.gradle`. 

I agree that we should add this to the readme for users that do not have those features enabled. 

@tobiasKaminsky what do you think?

**Comment by tobiasKaminsky** [comment]
I always expected that Android Studio will warn if there are different java versions set.
But yes, let us as at least add it to readme.
