### ISSUE TITLE
Remove select_account_unknown_error_toast toast

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#124]
In `AccountImporter::onActivityResult` you are making a toast with the (translated) text `select_account_unknown_error_toast`. This feels very strange, **please remove it.**

This can happen e.g. if the user presses the back button while he is picking an account. In this case, it is disproportionate to display a text that might make the user feel unsecure as it implies an error or an mistake - but it does not have to be necessarily. **Just print a log** or you might even throw an exception, but it is up to the 3rd-party-app to handle an abortion of an import. 

![ezgif-5-b3c0e91c0bf0](https://user-images.githubusercontent.com/4741199/66633800-f1616c80-ec0b-11e9-9580-2f9ba6d6af3d.gif)

**Comment by tobiasKaminsky** [comment]
Totally true, we should return an exception to 3rd party app.
