### ISSUE TITLE
Provide more information in Readme

### ISSUE THREAD

**Issue by korelstar** [nextcloud/Android-SingleSignOn#13]
This seems to be an interesting project. However, the Readme file is very narrow. I can't get which functionality this library provides. It would be nice to add a short paragraph to the `README.md`which gives some information about the goals and features of the library as well as its limitations.

Thanks!

**Comment by tobiasKaminsky** [comment]
@korelstar currently this project is under heavy developement, you can find a new Readme here: https://github.com/nextcloud/Android-SingleSignOn/blob/sso/README.md

Please give us feedback, if this is understandable and fits your need.

**Comment by tobiasKaminsky** [comment]
TODO:
- after first stable release, update jitpack dependency
- add more images of workflow 
	- show account chooser

**Comment by korelstar** [comment]
Thanks, that looks much better :smile:  :+1: 

One thing is left open: Does the user needs to install the Nextcloud (files) app on her/his device in order to use another Nextcloud app which uses this library?

**Comment by korelstar** [comment]
This should be noted explicitly in the `README.md` then. It's an important limitation.

**Comment by David-Development** [comment]
@korelstar Good point, thank you! Added it in #21.

**Comment by korelstar** [comment]
Thanks!
