### ISSUE TITLE
Remove unused AIDL Interface

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#130]
@tobiasKaminsky I just saw that there are two aidl interfaces in the repo.. I think those are some leftovers from renaming the namespace.. isn't it? I think we can remove one of them it.

https://github.com/nextcloud/Android-SingleSignOn/blob/110b781699d21320a1a1be54b648db27dd035e4d/src/main/aidl/com/nextcloud/android/sso/helper/IInputStreamService.aidl

**Comment by tobiasKaminsky** [comment]
I will clean this up after #128 is merged
