### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#14]
I can think we need to catch/handle the following "error" cases within this library.

- [x] User requests account (nextcloud app is not installed)
- [x] Account has been deleted from Android 
- [x] Account has been modified (do we need to know that?) (do we care?)
- [x] Incompatible app versions

**Comment by David-Development** [comment]
@tobiasKaminsky fyi: I'm working on this right now

**Comment by tobiasKaminsky** [comment]
:+1: 
1) according to your flow chart, this is already there?
2) yes, this indeed should be handled correctly
3) the 3rd party app is only storing the account name and a token to verify. Those values are not allowed to be changed. If on server side the password is changed, the 3rd party app does not need to care as this is handled by files app.

**Comment by David-Development** [comment]
Exception handling for case 1-3 was added in https://github.com/nextcloud/Android-SingleSignOn/commit/70831be877652f096b4998712ce83f5664a76b98
