### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#15]
I think it would be great to have some kind of versioning available (here and in the files app as well). 

Let's say there's a bug in the nextcloud files apps implementation (for a specific version). As a developer I want to be able to tell the user to upgrade the files app if there's a known issue with the version he's using right now. 

This means, that this would have to be implemented in the nextcloud files app as well. 

What do you guys think?

**Comment by tobiasKaminsky** [comment]
The files app has already release versions (2.0, 3.0, currently 3.2).
And for this library we will also do releases, which then can be used via jitpack:
android-SingleSignOn-0.1 / android-SingleSignOn-0.5 and so on.

Or do I understand you wrong?

**Comment by David-Development** [comment]
Let me describe the usecase in german:

Rein hypothetisches Beispiel:
Nutzer A hat die Nextcloud Files App in Version 3.0 installiert. Nun hat Version 3.0 einen Fehler im Netzwerkstack der bereits in Version 3.2 behoben wurde. Ich als Entwickler der news app möchte die Version der Files App prüfen können, um den Nutzer darauf hinzuweisen, dass er die Files App bitte updaten soll um den bekannten Fehler zu umgehen.

Hoffe das macht den Anwendungsfall etwas klarer.

**Comment by tobiasKaminsky** [comment]
Ah. Ok. So you want to have the possibility to query the files app version.
This should be possible, I guess.

I would then go even further and say, that we need a mechanism, that shows an exception to the 3rd party app, if the used library is not compatible to the files app:
3rd party app uses lib 1.1, which requires to files app >= 3.2.

If an user now has only files app 3.0 installed, our library should return an exception to the 3rd party app that the files app is too old.

We can check this during instantiating NextcloudAPI?

**Comment by David-Development** [comment]
Yes, exactly! 

Yes, I think the `NextcloudAPI` would be the right place. I also added it to the list of errors that we need to handle #14 .

**Comment by David-Development** [comment]
Fixed by cb598c2c6b16dd7b7989ad5a1da21674b97b4c5d
