### ISSUE TITLE
SSO incompatible to Retrofit2 version 2.7.0

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/Android-SingleSignOn#150]
Our dependabot opened a PR to update retrofit from 2.6.2 to 2.7.0, but when i ran our app the first time, the app dies instantly at startup. A little investigation discovered that the following validation method is gone:
https://github.com/nextcloud/Android-SingleSignOn/blob/186591c64e1577fb7d2678447455204efc3a7d4e/src/main/java/retrofit2/NextcloudRetrofitApiBuilder.java#L26 

So currently i can not upgrade to 2.7.0.

**Comment by desperateCoder** [comment]
see dependabot PR: https://github.com/nextcloud/Android-SingleSignOn/pull/156

this would fix the issue, but there is one incompatibility i already resolved in my fork:
https://github.com/desperateCoder/Android-SingleSignOn/commit/ad266b943bbfc154c5e3d6cc4f95c0a3caf4d2ac

you can apply my commit or wait for my PR (may take a while... :smile: )

**Comment by tobiasKaminsky** [comment]
Thanks Arthur <3

**Comment by desperateCoder** [comment]
Your'e very welcome buddy! <3
