### ISSUE TITLE
Add retrofit helper/wrapper functions

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#17]
Another question is, if we should add the following class, which provides some helpful retrofit/rxjava methods to this library. I think we should, but in case we add it, we have to add the retrofit/rxjava dependencies to this library as well. But I think most apps use retrofit anyways.. right? Especially with this library it's really easy to use..

https://github.com/nextcloud/news-android/blob/master/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/reader/nextcloud/API_SSO_Helper.java

**Comment by tobiasKaminsky** [comment]
I am not sure if and how many apps are using it…Maybe we should ask the mainainters of our known apps.

Do you know how big the additional dependencies are?
(this would then only be overhead, if the app is not using retrofit/rxjava)

**Comment by David-Development** [comment]
>Maybe we should ask the mainainters of our known apps.

sounds like a good idea!

>Do you know how big the additional dependencies are?

no.. is there any way to measure this?


>this would then only be overhead, if the app is not using retrofit/rxjava

exactly!

**Comment by tobiasKaminsky** [comment]
I just build the library and compared the aar size: it is only 4kb bigger.
So, I would say, that we can include it.

**Comment by David-Development** [comment]
Okay, perfect. Thank you! I think it makes sense to integrate it into this library then since this is "duplicate" code if every developer has to implement it for himself. And we can make this "wrapper/helper" even more bullet proof if other developers find some issues in it.

**Comment by mario** [comment]
I use both RxJava(2) and Retrofit, so ++.
