### ISSUE TITLE
Minor issue: Text contrast in dialogs insufficient

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#187]
Google Play Store Pre-launch report says:

![Bildschirmfoto am 2020-03-17 um 10 41 41](https://user-images.githubusercontent.com/4741199/76843434-1487ec00-683c-11ea-8789-1bf62319cfb0.png)

![Bildschirmfoto am 2020-03-17 um 10 45 05](https://user-images.githubusercontent.com/4741199/76843642-60d32c00-683c-11ea-884f-843cc41ee3db.png)

![Bildschirmfoto am 2020-03-17 um 10 44 21](https://user-images.githubusercontent.com/4741199/76843565-47ca7b00-683c-11ea-8db7-ec06f16d710d.png)

By the way, the `warn`-icon of the last screenshot looks so terrible in combination with material design. Could you please remove it or at least ship a [corresponding material icon](https://material.io/resources/icons/?search=warn&icon=warning&style=baseline)?

**Comment by penguin86** [comment]
It seems like it depends on the theme. I've had the same report during a F-Droid pre-release review. This is the attached screenshot:
![Screenshot](https://gitlab.com/fdroid/fdroiddata/uploads/8d39ff4d0b02b97d9098d76dbeeeef28/2021-09-24_22.01.42.jpg)

**Comment by stefan-niedermann** [comment]
Closing because:

- First screenshot is no longer valid since [we don't use links anymore in the description of dialogs](https://github.com/nextcloud/Android-SingleSignOn/commit/67d7feddfbabb62cfc6f9327abd8693124317347)
- Second screenshot is invalid because we use the default Material 3 themed dialog generated by `MaterialAlertDialogBuilder`
- Third screenshot is no longer valid since [we dropped the icons](https://github.com/nextcloud/Android-SingleSignOn/commit/bb0c5c732146c2fcc2aff40c2c6fb3e9742dd67b)
