### ISSUE TITLE
Theming issue with permission dialog on Android 10

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#195]
Hey guys,

i have a theming issue with the "Grant Permission"-dialog on Android 10. As you can see in the screenshot, the "Cancel" and "OK"-button have white color, they are only discoverable when focussed:

![device-2020-04-08-121239](https://user-images.githubusercontent.com/4741199/78772935-c70e2300-7992-11ea-96da-39fa1607e629.png)

![Bildschirmfoto vom 2020-04-08 12-13-56](https://user-images.githubusercontent.com/4741199/78772944-caa1aa00-7992-11ea-9f51-594d80b9693a.png)

Unfortunately i am not sure whether this is caused by the way SSO starts the dialog or by the theming of the 3rd-party-app. Since i have it in the Deck app *and* the Notes app i think it might caused by the SSO-lib.

This might be also a relevant reference: https://github.com/stefan-niedermann/nextcloud-notes/issues/784

@David-Development can you reproduce this with the News-app?

**Comment by David-Development** [comment]
@stefan-niedermann ugh.. oh.. when did this happen? 😟 Same for the news app! It did work before and I tested it on that specific device. Can't remember updating the news app. Maybe this is related to a  Nextcloud files app update? The files app provides this dialog, right? 

@tobiasKaminsky did you guys change anything? 😅

**Comment by tobiasKaminsky** [comment]
Yes, somehow.
For some reason this is/was tinted and due to dark mode there was a change and this broke it.

**Comment by stefan-niedermann** [comment]
Well, that was quick :D
