### ISSUE TITLE
Android Studio Network Profiler not usable

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#199]
A great tool is the [Android Studio Network Profiler](https://developer.android.com/studio/profile/network-profiler). Unfortunately it seems to be useless in combination with tge SSO library.

The 3rd-party-client doesn't show any traffic at all, that's fine because the actual traffic is done by the main app.

Analysing the main app shows, that some traffic occurs, but one cannot see the single requests and responses.

According to Google, the Network Profiler supports only `HttpUrlConnection` and `OkHTTP`. I thought, that the main app does the requests with one of those libs, huh?

Maybe this is even a bug in the main app. However, it would be great and helpful to be able to use this tool.

cc @desperateCoder

**Comment by tobiasKaminsky** [comment]
> According to Google, the Network Profiler supports only `HttpUrlConnection` and `OkHTTP`. I thought, that the main app does the requests with one of those libs, huh?

Not yet. 
We are in the process of switching, but this takes some time.

**Comment by stefan-niedermann** [comment]
What are you using right now if not `HttpURLConnection`?

**Comment by tobiasKaminsky** [comment]
The old http apache client, e.g.  org.apache.commons.httpclient

**Comment by stefan-niedermann** [comment]
Shall we keep this issue open for tracking purposes or shall we close it since it will be fixed "at some point in the future"?

**Comment by tobiasKaminsky** [comment]
Closing it…but keep it in mind ;-)
