### ISSUE TITLE
Import Account from Nextcloud Android App don't work

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/Android-SingleSignOn#209]
**Steps to reproduce:**
* Login with a Account into Nextcloud Android
* Open example Nextcloud Talk
* Select Option "Import Account from the App Nextcloud"
* Select the previous Account
* The Connection Dialog is visible, after fiew seconds the Login Screen appears

Nextcloud Server 18.0.4
Nextcloud Android 3.11.1
Nextcloud Talk 8.0.9

*Mobile Device:*
- Samsung Galaxy Note 9 | Android 10 
- Xiaomi Redme Note 8 | Android Miui 11 

**Youtube Screencast**
https://youtu.be/QximmjTxTeY

**Comment by stefan-niedermann** [comment]
Hi @mr-bolle,

the Talk app does not support the Single-Sign-On mechanism provided by this library and never did (https://github.com/nextcloud/talk-android/issues/822).

Though it seemed to be able to import an existing Android account in the past (https://github.com/nextcloud/talk-android/issues/710).

You should asked in one of the linked issues or open a [new issue in the Talk repository](https://github.com/nextcloud/talk-android/issues/new).

Regards
