### ISSUE TITLE
Spotbugs is not compatible with Gradle 6

### ISSUE THREAD

**Issue by burningthumb** [nextcloud/Android-SingleSignOn#218]
I updated to Android Studio 4.0 and it in turn wanted me to update to Gradle Plugin 4.0.0 and Gradle version 6.1.1.  After doing so, the project will not build because Spotbugs is using deprecated methods of some kind.  I can't recall the exact details but if you update you will see it.  For now, I simply removed Spotbugs and I can build but I suppose you will want (maybe already have) a "better" solution than that so I have not created a pull request.  I just raise this issue in case you are not aware of the problem and so that anyone else using android-sso will know the exact cause of the build problem and one solution.

**Comment by AndyScherzinger** [comment]
@burningthumb thanks for the info, we are working on this, see https://github.com/nextcloud/android/pull/6180 which is why we currently stay on Android Studio 3.6

**Comment by burningthumb** [comment]
Sure.  From my side, I just removed spotbugs and everything built fine on Android Studio 4.0 with Gradle 6.1.1 but I completely understand if you have bigger issues.

**Comment by AndyScherzinger** [comment]
We just merged the AS4 update for the Android client, so the client library and the SSO library will follow soon 👍

**Comment by tobiasKaminsky** [comment]
This is already fixed.
