### ISSUE TITLE
Connection issues after updating Nextcloud Files App

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#24]
When the user keeps the client app open in the background (e.g. news) the news app won't work after updating the Files App. Most likely due to the service connection that was killed.

**Comment by David-Development** [comment]
As I found out, the callback `onServiceDisconnected` ([NextcloudAPI.java](https://github.com/nextcloud/Android-SingleSignOn/blob/master/src/main/java/com/nextcloud/android/sso/api/NextcloudAPI.java)) will be called once the Nextcloud Files App gets killed (e.g. while installing a new version of the files app). We somehow need to reconnect the service at this point. To reconnect the API, we can just make a call to `start()`.

The problem is, that we don't have the context available there.. Holding a reference to the context inside the `NextcloudAPI` might be a possible memory leak? Or am I wrong here.. ?

@tobiasKaminsky Any ideas?

**Comment by David-Development** [comment]
This solution works pretty well even while reinstalling the nextcloud files app. Or when the files app gets killed by the user, the api disconnects for a second. But it will be automatically reconnected due to the code provided above.

@tobiasKaminsky Can you review this and give some feedback?

**Comment by tobiasKaminsky** [comment]
Can we maybe limit the context to only those functions we need, via an interface?
So that we cannot access context directly?
If not, we shall evaluate the impact on the context, as the context is passed via API to files app, or? But other 3rd party apps should be able to misuse this, or?

Other then that I am fine with this approach.

**Comment by David-Development** [comment]
> Can we maybe limit the context to only those functions we need, via an interface?

What exactly do you mean by that? Do you mean that we should pass the context into those function as an argument (where the context is required)? We could do that, but in order to reconnect the api, we need an context to bind the service to. So we need to remember what our context was is the beginning.

> as the context is passed via API to files app

The context is used to bind the service that handles the communication between the two apps. The context is not passed - at any point in time - to the files app. It's only purpose is to connect the api service. (`context.bindService(...)`)

I did some more research today and noticed, that if you use the `NextcloudAPI` in combination with a DI Library such as Dagger, there shouldn't be any problems since the `Application` even survives rotations etc. (it lives longer than Activitys). Therefore the context won't change over time and we shouldn't have any problems with memory leaks. 
However if you pass an Activity as context to the `NextcloudAPI`, you'll need to make sure that you properly call `stop()` before the Activity ends (e.g. on rotation change).  I already updated the README accordingly (Section: "(4.2) Without Retrofit")

**Comment by tobiasKaminsky** [comment]
Is this still valid?

**Comment by David-Development** [comment]
I think we are good to close this one.
