### ISSUE TITLE
Small contribution: An real world example project.

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/Android-SingleSignOn#262]
Hi everyone,
I am working on an client for my [Quicknotes](https://github.com/matiasdelellis/quicknotes) application using this library. I had good comments, and proposals to help me with this library of some of you. But instead of focusing on my application, I thought it was more convenient to join forces to do a good example application.

So my proposal was to develop a client example for the nextcloud [app-tutorial](https://github.com/nextcloud/app-tutorial), and reducing much of the development of my application, I quickly got an example that works with the application.

* https://github.com/matiasdelellis/app-tutorial-android
* https://github.com/matiasdelellis/app-tutorial-android/releases/tag/1.0prerelease

### Some screenshots:
Choose account | Initial view | Note edition | Grid View | Sidebar | About
 ---- | -- | -- | -- | -- | --
![Choose account](https://github.com/matiasdelellis/app-tutorial-android/raw/master/doc/screenshots/nextcloud-app-tutorial-android-login.png) | ![Initial view](https://github.com/matiasdelellis/app-tutorial-android/raw/master/doc/screenshots/nextcloud-app-tutorial-android-empty-view.png)  |![Note edition](https://github.com/matiasdelellis/app-tutorial-android/raw/master/doc/screenshots/nextcloud-app-tutorial-android-note-editor.png) | ![Grid View](https://github.com/matiasdelellis/app-tutorial-android/raw/master/doc/screenshots/nextcloud-app-tutorial-android-note-grid-view.png) | ![Sidebar](https://github.com/matiasdelellis/app-tutorial-android/raw/master/doc/screenshots/nextcloud-app-tutorial-android-sidebar.png) | ![About](https://github.com/matiasdelellis/app-tutorial-android/raw/master/doc/screenshots/nextcloud-app-tutorial-android-about.png)

It is basic, it has many things hardcoded (Especially in the styles), a lot of copypast from other projects like Netcloud Notes, Official Android client, etc (Thanks!!!.), and it's probably 100% functional, but surely there are things to improve.

So, would like you to give it some kind of review, and I hope it will be useful for others. 😄

**Comment by stefan-niedermann** [comment]
I like the idea of a minimal sample app, but it should be independent of any 3rd party apps and only rely on the files app IMHO - e.g. displaying the name of the current user and the number of files?

**Comment by matiasdelellis** [comment]
> I like the idea of a minimal sample app, but it should be independent of any 3rd party apps and only rely on the files app IMHO - e.g. displaying the name of the current user and the number of files?

The idea of using an notes application is that it allows you to implement a complete CRUD (and that is why note applications are the "Hello world" since the time of Visual Basic. haha,), and this particular case is well [documented](https://docs.nextcloud.com/server/20/developer_manual/app_development/tutorial.html#adding-a-restful-api-optional). Don't think it as an "application", since it is the result of a tutorial, and the idea of my example would be a continuation of this tutorial.

So, for that the example have sense, it would have to be documented in another tutorial... but maybe it would be difficult to focus on Nextcloud, since the most interesting code for Nextcloud is very small. :thinking:

I do not know if I could write this tutorial, and having said all the above, now don't know if it makes sense to do so, since it will be just yet another Android Studio tutorial.

I support your idea of doing a more minimal example, but it should include at least the login, change users, and a minimum CRUD.

Thanks for all,
Regards,
Matias.

**Comment by tobiasKaminsky** [comment]
For having a small example I do not mind that notes api is used.
Mainly it is an example on Android's side…

I would say, go ahead :-D
It should then be in its own repo, I think…

**Comment by stefan-niedermann** [comment]
So, we now have a [minimal sample app as a separate module within this repository](https://github.com/nextcloud/Android-SingleSignOn/tree/master/sample) for testing and demonstration purposes, closing this issue therefore.

@matiasdelellis it would be awesome though if you could file a Pull Request for adding your app to the [`Known apps` section of the README.md](https://github.com/nextcloud/Android-SingleSignOn#known-apps) :slightly_smiling_face:
