### ISSUE TITLE
Allow multiple parameters with same key

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#273]
While helping to implement SSO for the Bookmarks app, i stumbled upon a nasty little missing feature in the SSO:

Each bookmark can have multiple tags, and [according to the API documentation](https://nextcloud-bookmarks.readthedocs.io/en/latest/bookmark.html#query-bookmarks) they need to be passed as parameters like following:

```
?tags[]=firsttag&tags[]=secondtag
```

So one needs multiple parameters with the key `tags[]`.

The current implementation of the `Builder` only offers to set the parameters with a `Map`: `setParameter(myMap)`. In Java, a map always has unique keys, so it is impossible to implement this API with the current approach.

My first idea was to ask @marcelklehr for changing the API, but in fact this API behavior [is even standardized](https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request/24728298#24728298) in `RFC 3986`, therefore the SSO should support it.

In fact this can be implemented **without any breaking change**:

1. Change internal data structure from `Map<String, String>` to something like `Collection<Pair<String, String>>`
2. Rewrite the implementation of `setParameter`: Keep the `Map<String, String>` as argument and clear the mentioned `Collection` from step 1 (to be fully downward compatible). Then transform the `Map` and add all entries to the `Collection`. Make clear in the documentation (and Javadoc) that previously set parameters will be deleted to maintain downward compatibility.
3. Annotate this method with `@Deprecated`
3. Offer new APIs: `addParameter(Collection<Pair<String, String>>)`, `addParameter(Pair<String, String>)`, `clearParameter()` and maybe `removeParameter(Pair<String, String>)` and maybe ` setParameter(Collection<Pair<String, String>>)` which could clear the previously added parameters

**Comment by David-Development** [comment]
I wasn't aware of the fact that you can have the same query parameter multiple times when I implemented this. 

@stefan-niedermann Your solutions sounds like a great idea to me. @tobiasKaminsky What do you think? Should we implement it that way?

**Comment by tobiasKaminsky** [comment]
Sure, sounds like a good plan :+1:

**Comment by dasbiswajit** [comment]
@David-Development @marcelklehr @tobiasKaminsky can we agree on a solutions? Its blocking this [PR](https://gitlab.com/bisada/OCBookmarks/-/merge_requests/40). Many thanks for help!

**Comment by desperateCoder** [comment]
@tobiasKaminsky  these are breaking changes to the files app: 

https://github.com/nextcloud/Android-SingleSignOn/compare/master...desperateCoder:273-multiple-params-for-key

Any ideas if/when/how the files app is going to support this? I can imagine this won't be that easy without breaking anything else...

**Comment by dasbiswajit** [comment]
Many Thanks @desperateCoder. @tobiasKaminsky details are in telegram channel.

**Comment by dasbiswajit** [comment]
#304

**Comment by yamanq** [comment]
Since the PR was merged, has this issue been fixed?

**Comment by stefan-niedermann** [comment]
Yes, but keep in mind that this solution also requires an uodate of thr Nextcloud files app. This PR has also been merged, but i might take some time until the new version has been oublished and spread for the majority of the users.
