### ISSUE TITLE
Some requests fail with code 520 after upgrading from 0.5.3 to 0.5.4

### ISSUE THREAD

**Issue by bubelov** [nextcloud/Android-SingleSignOn#276]
I've noticed that some parts of my app stopped working due to some strange HTTP request failures. To add some context: it's an RSS reader app and it uses the following method to notify a server of read news items:

```kotlin
@PUT("items/read/multiple")
fun putRead(@Body args: PutReadArgs): Call<ResponseBody>
```
Here is the args model:

```kotlin
data class PutReadArgs (
    val items: List<Long>,
)
```
And that's how I call it:
```kotlin
api.putRead(PutReadArgs(ids))

if (!response.isSuccessful) {
    throw response.toException()
} 
```

This call always return HTTP code 520 on 0.5.4. Downgrading to 0.5.3 solved the issue.

**Comment by tobiasKaminsky** [comment]
What exception do you get?

**Comment by bubelov** [comment]
@tobiasKaminsky here is what I could scrap:

```
Response{protocol=http/1.1, code=520, message=Response.error(), url=http://localhost/}
```

```
errorBody: java.lang.IllegalStateException: Could not instantiate "class okhttp3.ResponseBody", because response was null.
```

And here is what happened in Logcat:

```
NextcloudRetrofitServiceMethod: NextcloudRetrofitServiceMethod() called with: apiEndpoint = [/index.php/apps/news/api/v1-2/], method = [public abstract retrofit2.Call co.appreactor.news.api.NextcloudNewsApi.putRead(co.appreactor.news.api.PutReadArgs)]
NextcloudAPI: performRequestV2() called with: type = [class okhttp3.ResponseBody], request = [NextcloudRequest(method=PUT, header={}, parameter={}, requestBody={"items":[5978]}, url=/index.php/apps/news/api/v1-2/items/read/multiple, token=null, packageName=null, accountName=null, bodyAsStream=null, followRedirects=false)]
AidlNetworkRequest: copy data from service finished
```

**Comment by David-Development** [comment]
@bubelov I think this error occurs as there is no response body. The API endpoint does not return anything therefore we can't instantiate the ResponseBody. (See [here](https://github.com/nextcloud/news/blob/master/docs/externalapi/Legacy.md#mark-multiple-items-as-unread)).

I double checked with my news app and I use `Call<Void>` which works well.

**Comment by bubelov** [comment]
@David-Development just tested it and it works like a charm with both versions of the library. Thanks for the tip!

**Comment by David-Development** [comment]
@bubelov Glad it works, thank you for the feedback. I think we can close this issue then, right?
