### ISSUE TITLE
Package visibility issue when targetSdk="30"

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#277]
Android [has changed the package visibility](https://developer.android.com/about/versions/11/privacy/package-visibility) starting with Android 11.

This means basically, if a 3rd party app increases its `targetSdk` attribute in the `AndroidManifest.xml`, then it will no longer be able to find the Nextcloud Files app. `AccountImporter#appInstalledOrNot` will always return `false`, because `PackageManager#getPackageInfo` will not return any infos about 3rd party packages.

I am currently trying to find a solution based on the [`queries` mentioned in step `7`](https://developer.android.com/about/versions/11/privacy/package-visibility#test) and will keep you up to date. Though this should not be done by the 3rd party app, but in the [`AndroidManifext.xml` of the SSO library](https://github.com/nextcloud/Android-SingleSignOn/blob/master/src/main/AndroidManifest.xml).

**Comment by tobiasKaminsky** [comment]
"queries" needs to be added to 3rd party app, right?

**Comment by stefan-niedermann** [comment]
Yes, i *think* so. But since 3rd party apps which use the SSO will *always* rely on that `query`, the `query` tag should be in the `AndroidManifest.xml` of the SSO library, no?

**Comment by tobiasKaminsky** [comment]
Ah right, they (3rd party) of course need to query files app.
I mixed it up somehow…

**Comment by stefan-niedermann** [comment]
side note: https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+blogspot/hsDu+(Android+Developers+Blog)&m=1
