### ISSUE TITLE
Add codacy checks to pull requests?

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/Android-SingleSignOn#28]
@tobiasKaminsky @David-Development I added Android SSO (and Android News) to the codacy checked repositories see e.g. https://app.codacy.com/project/Nextcloud/Android-SingleSignOn/dashboard

Should I also add the codacy checks to the PRs like we do for the files app and the android library repositories?

**Comment by David-Development** [comment]
> I added Android SSO (and Android News) to the codacy checked repositories

Awesome!! Thank you 👍 

> Should I also add the codacy checks to the PRs like we do for the files app and the android library repositories?

I'm not sure if I get the question correctly. This repository (`Android-SingleSignOn`) as well as the `news-android` repository don't have open PR's anymore. It's already merged on master (in both repositories).

**Comment by AndyScherzinger** [comment]
> I'm not sure if I get the question correctly. 

My question is if I should activate codacy for PRs for the repositories. If I do this will be a PR check run on every (future) PR which would block merges (except for forced, admin merges) if codacy detects any new issues caused by the PR in comparison to the master branch. (Like you see in the files app repo for the SSO branch/PR)

**Comment by AndyScherzinger** [comment]
@David-Development I also invited you to the codacy admin team. This way you can always set issues to be ignored or customize the rules that get checked e.g. for pmd, checkstyle, etc. :)

**Comment by tobiasKaminsky** [comment]
Yes, I think we should enable this.
And, as dev speed slows down, also prevent pushing directly to master.

**Comment by David-Development** [comment]
Yes, I think it's a good idea to keep code quality up! :) I'll try to fix some code-quality issues later today!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you activate the post commit hook in codacy? I do not have any rights on the repos atm.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please also activate it for Android News client :) :heart:

**Comment by tobiasKaminsky** [comment]
@David-Development can you then please invite @nextcloud-android-bot and make him an admin in your repo?

**Comment by David-Development** [comment]
@tobiasKaminsky to the nextcloud/news-android repo on GitHub? I don't have admin right there..

**Comment by tobiasKaminsky** [comment]
No problem, nextcloud-android-bot is added and codacy is now working :+1:
