### ISSUE TITLE
Retrofit NetworkOnMainThreadException with Observable<ResponseBody>

### ISSUE THREAD

**Issue by friltase** [nextcloud/Android-SingleSignOn#286]
I get NetworkOnMainThreadException when executing request with NextcloudRetrofitApiBuilder, despite using `Schedulers.io()` 

I'm trying to use retrofit to fetch a file, my retrofit: 
```kotlin
@GET("{fileName}")
fun fetchFile(@Path("fileName") fileName: String): Observable<ResponseBody>
```
Request: 
```kotlin
val service = NextcloudRetrofitApiBuilder(api, "/remote.php/webdav/").create(NextCloudService::class.java)
service.fetchFile("Readme.md")
          .subscribeOn(Schedulers.io())
          .observeOn(AndroidSchedulers.mainThread())
          .subscribe {
          }
```
Exception is thrown by `performAidlNetworkRequest` in `AidlNetworkRequest`
I suspect this is because of this line in `NextcloudRetrofitServiceMethod`
```kotlin 
if(typeArgument == ResponseBody.class) {
    return (T) Observable.just(Okhttp3Helper.getResponseBodyFromRequest(nextcloudAPI, request));
}
```
Here `Observable.just` is used which causes the `getResponseBodyFromRequest` to be executed on current thread (which in my case is MainThread). I think using `Observable.fromCallable` would solve this issue. 

My dependencies: 
```
implementation 'com.github.nextcloud:Android-SingleSignOn:0.5.4'
implementation 'com.squareup.retrofit2:retrofit:2.9.0'
```
```
android.os.NetworkOnMainThreadException
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequest(AidlNetworkRequest.java:221)
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:191)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:160)
        at com.nextcloud.android.sso.helper.Okhttp3Helper.getResponseBodyFromRequest(Okhttp3Helper.java:39)
        at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.invoke(NextcloudRetrofitServiceMethod.java:181)
        at retrofit2.NextcloudRetrofitApiBuilder.lambda$create$0$NextcloudRetrofitApiBuilder(NextcloudRetrofitApiBuilder.java:30)
        at retrofit2.-$$Lambda$NextcloudRetrofitApiBuilder$4bW56NwwdhdtTjcg5dzPnac7Zv8.invoke(lambda)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy0.fetchFile(Unknown Source)
```
   
I just started working with this library, perhaps I'm missing something. 
Thanks

**Comment by tobiasKaminsky** [comment]
@David-Development as you are most experience with retrofit

**Comment by David-Development** [comment]
@friltase Thanks for the report. I'm not sure what's happening here. Maybe you can share the project? 

To be honest, from what I can see, your code looks perfectly fine. I'm using pretty much the same snippet for making a similar request (see https://github.com/nextcloud/news-android/blob/0a4882430e21c737a46e3bf7052e518d11883ee4/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListDialogFragment.java#L236)

```java
mApi.getNewsAPI().renameFeed(feedId, paramMap)
                        .subscribeOn(Schedulers.newThread())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Action() {
```

Somehow your request is still made from the main thread (as the exception indicates). The method you mentioned is defined here: https://github.com/nextcloud/Android-SingleSignOn/blob/master/src/main/java/com/nextcloud/android/sso/helper/Okhttp3Helper.java#L39 and as you can see, it's actually starting the network connection right there (behind the scenes there is much more happening as the actual request is made by the files app).

**Comment by friltase** [comment]
@David-Development 
I created sample project, available [here](https://github.com/friltase/TestRetrofitSSO).

Your example is a bit different, your return type is `Completable`. The problem I have is only visible when trying to return `okhttp3` `ResponseBody.class`.  
```kotlin
if(typeArgument == ResponseBody.class) {
    return (T) Observable.just(Okhttp3Helper.getResponseBodyFromRequest(nextcloudAPI, request));
}
```
In my sample app I also created a working example.
```koltlin
@GET("cloud/user?format=json")
    fun user(): Observable<OcsUser>
``` 
This request uses `NextcloudRetrofitServiceMethod`
```kotlin
return (T) nextcloudAPI.performRequestObservableV2(typeArgument, request).map(r -> r.getResponse());
```
Inside its implementation there is `Observable.fromPublisher` which is working fine.

**Comment by David-Development** [comment]
@friltase Looks like this is indeed a bug. `Observable.just(..)` executes the network request immediately on method invocation. I replaced it now with an `Observable.fromCallable(() ->...)` to execute it in the appropriate subscribe thread and it works now.  Thanks for the great sample app!

@desperateCoder didn't you guys run into any issues? I saw that you are downloading attachments using the `ResponseBody` type as well 😅 But I think you have another layer of async things around it, eh?

**Comment by desperateCoder** [comment]
Sorry, forgot to respond :/
> saw that you are downloading attachments using the ResponseBody type as well

No idea if this is still interesting but yea, we have:
https://github.com/stefan-niedermann/nextcloud-deck/blob/f29eed9db4c0906fa7887e446cf0325718ef6827/app/src/main/java/it/niedermann/nextcloud/deck/api/DeckAPI.java#L129

> But I think you have another layer of async things around it, eh?

Exactly:
https://github.com/stefan-niedermann/nextcloud-deck/blob/f29eed9db4c0906fa7887e446cf0325718ef6827/app/src/main/java/it/niedermann/nextcloud/deck/api/RequestHelper.java#L34-L38

But thats not even all, we also often use vanilla-Java like:
https://github.com/stefan-niedermann/nextcloud-deck/blob/f29eed9db4c0906fa7887e446cf0325718ef6827/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/SyncManager.java#L112-L115

Hope that helps. Feel free to steal everything usable from our code, but i doubt that we do something really different than you guys.
