### ISSUE TITLE
Single sign-on does not work on Android API 21-26

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#30]
There are some issues when the apps have a different signing. As described [here](https://stackoverflow.com/questions/51211980/accountmanager-getauthtoken-securityexception-on-api-21-23-working) the dialog won't appear (it's just stuck forever). I can't seem to find a way to solve this issue. Any ideas are welcome! Otherwise we might have to implement our own authentication manager..

In the logcat I can see the following error message (from the nextcloud files app). I even tried adding permissions handling again - still doesn't work.. 

```java
java.lang.SecurityException: KEY_INTENT resolved to an Activity (android.accounts.GrantCredentialsPermissionActivity) in a package (android) that does not share a signature with the supplying authenticator (nextcloud).
        at com.android.server.accounts.AccountManagerService$Session.checkKeyIntent(AccountManagerService.java:4230)
        at com.android.server.accounts.AccountManagerService$Session.onResult(AccountManagerService.java:4394)
        at com.android.server.accounts.AccountManagerService$8.onResult(AccountManagerService.java:2556)
        at com.android.server.accounts.AccountManagerService$8.onResult(AccountManagerService.java:2505)
        at android.accounts.IAccountAuthenticatorResponse$Stub.onTransact(IAccountAuthenticatorResponse.java:59)
        at android.os.Binder.execTransact(Binder.java:565)
```

**Comment by David-Development** [comment]
I found a workaround. However I'm not sure what the security risks are.. (http://blog.udinic.com/2013/04/24/write-your-own-android-authenticator/)

Add `android:customTokens="true"` to the `authenticator.xml` in the nextcloud files app. I can't find any documentation what it does exactly. It definitely removes the dialog that usually appears asking the user if he want's to allow access to that account.

**Comment by David-Development** [comment]
@tobiasKaminsky I hacked something together.. (wrote a small activity that asks the user to grant permission to access the account. If the user clicks on yes, it'll return the token in the intent). Therefore we can get rid of the AccountManager.. And it works on all devices.. and we can design the account request dialog in the nextcloud style! :) 

What do you think? Should I upload my changes to a branch called "sso"? Or do I need to give it another name since it's already been used once?

**Comment by AndyScherzinger** [comment]
I'd say feel free to use "sso" for the branch name, I do the same thing with "codacy" all the time :)

**Comment by tobiasKaminsky** [comment]
Cool idea, @David-Development. But what about security? I fear that intents can be intercepted…(at least we have to make sure that we use explicit intents)

**Comment by David-Development** [comment]
@tobiasKaminsky I'm no security expert but I think intercepting intents is not possible on a "normal" Android Device. And we're already using "somewhat" explicit intents as we specify the exact package-name and activity that we want to start (no intent-filter). 

Explicit only work in your own app, right? Because you'll reference the class that you want to call directly. That's not possible for us. Even if someone would manage to intercept the intent, there's nothing he can see, right? I mean the intent does not contain any information at all (except for account name). Only the response intent (which will be delivered back to the calling activity through android) will include the token.

**Comment by tobiasKaminsky** [comment]
Yes, the intent back with the token is maybe the problem. But as you said, we use the exact package name, so I hope we are fine.

**Comment by David-Development** [comment]
Can we close this issue now?

**Comment by AndyScherzinger** [comment]
I think so yes :+1: but we can wait or @tobiasKaminsky since he is also testing this for the 3.3.0 RC3 today

**Comment by tobiasKaminsky** [comment]
Working fine with 3.3.0
