### ISSUE TITLE
Hint when Nextcloud is not installed - on other platforms

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#305]
When the Nextcloud app is not installed, the lib prompts a dialog with a link to the Play Store.
Since the Nextcloud app is not available only on the Play Store, i am wondering whether we need flavors for the SSO library - like Play Store, F-Droid and AppGallery. This way we could target them to different stores.

Alternatively we should think about the wording and (even if it hurts a bit) remove the link to one hardcoded store entry?

Another idea was to make it possible to pass the error message and the link from the 3rd-party apps.

Any ideas?

**Comment by tobiasKaminsky** [comment]
On Files we use this:
https://github.com/nextcloud/android/blob/54589b42b4f4e5c8f45c9e1b9b511c7398c48588/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java#L791-L804

As NC appId is same on Fdroid and Gplay it should work.

**Comment by stefan-niedermann** [comment]
Given you have only installed F-Droid:
The text still says "Install from Google Play Store" - yes, clicking on it will lead you to F-Droid, but it is confusing.

Also i am not sure whether this works properly for app gallery as i don't have a huawei device :-/

**Comment by tobiasKaminsky** [comment]
True, then we should change the string to be more generic.
Huawei I also cannot test.

**Comment by stefan-niedermann** [comment]
I *guess* that the `market://` intent should also work for the App Gallery, and since you have the same app id in the App Gallery as in Play Store and F-Droid, it maybe is enough if we just change it to "Install the Nextcloud app first" (where `Nextcloud app` is linked) - to not mention any app store directly?

**Comment by David-Development** [comment]
>change it to "Install the Nextcloud app first"

Sounds great!

>not mention any app store directly?

How do we know which one to open though? Is there any way to find out where the current app was installed from? If not - we could add a dialog where the user can pick his preferred store from

**Comment by stefan-niedermann** [comment]
> How do we know which one to open though?

I think we don't actually need to know it - Isn't that the whole idea of the intent system of android? "Hey! I have something here, who can handle it?" and Android uses the app which is able of handling it or provides a chooser when multiple apps are able to handle it.

I think that the `market://` intent *should* open the only installed store *or* provide a chooser if multiple are installed.

So we need only to adjust the wording to something neutral and use the `market://` link similar to how @tobiasKaminsky is opening DAVx5 in the files app...

**Comment by stefan-niedermann** [comment]
Fixed in https://github.com/nextcloud/Android-SingleSignOn/commit/67d7feddfbabb62cfc6f9327abd8693124317347#diff-ee487ebad0a1f1bd6f98e9d1b9450cd5f789774755f19904eee13a6f32e00f47L37 - All hard coded links to the Google Play Store have been replaced with generic `market://details?id=com.nextcloud.client`
