### ISSUE TITLE
Android App causes AD/LDAP Account lockout

### ISSUE THREAD

**Issue by mightymop** [nextcloud/Android-SingleSignOn#333]
see Issue: https://github.com/nextcloud/android/issues/8302

**Comment by stefan-niedermann** [comment]
@mightymop why are you posting this here? Is this in any relation to the Android SingleSignOn mechanism with a 3rd party Android app?

Note that this SingleSignOn library is to authenticate between 3rd party Android apps and the Nextcloud Android app.

**Comment by mightymop** [comment]
> 
> 
> @mightymop why are you posting this here? Is this in any relation to the Android SingleSignOn mechanism with a 3rd party Android app?
> 
> Note that this SingleSignOn library is to authenticate between 3rd party Android apps and the Nextcloud Android app.

Sorry, i thought this lib interacts with the android app when creating the android nextcloud account... 
Atm it is not clear for where the problem starts ... after reboot and / or hard kill of the app recreation/relogin seems ok ...

**Comment by stefan-niedermann** [comment]
No, this lib enables a 3rd party app like Notes Android, News Android or Deck Android the communication with the Nextcloud Android app 🙂

**Comment by mightymop** [comment]
> 
> 
> No, this lib enables a 3rd party app like Notes Android, News Android or Deck Android the communication with the Nextcloud Android app 🙂

hm ok then, the name is a bit confusing ;)

**Comment by stefan-niedermann** [comment]
Not really, connecting to the Nextcloud Android app will result in not needing to enter the account credentials again, so from the perspective of a user one only needs to sign on once to use various apps :)
