### ISSUE TITLE
Documentation in README.md is outdated

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#34]
Hi @David-Development ,

it seems like the documentation in the README.md file is outdated. Can you please update it to match the version 0.1.2?

**Comment by David-Development** [comment]
@stefan-niedermann ohh, you're right! Thank you for the reminder! Just fixed it :)

**Comment by stefan-niedermann** [comment]
Actually i meant that some of the code examples do not work anymore, like

`AccountImporter.GetAuthTokenInSeparateThread(context, account);`
