### ISSUE TITLE
Headers not sent?

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/Android-SingleSignOn#36]
Hi, 
I am currently trying out the new "If-Modified-Since" Header for Nextcloud-Deck (see https://github.com/nextcloud/deck/issues/659) (thanks @juliushaertl for this feature!)

this is setting the Header (am i doing it right so far?):
``` java

 private NextcloudRequest.Builder buildRequest(String method, String path, Date lastSync) {
        NextcloudRequest.Builder builder = new NextcloudRequest.Builder()
                .setMethod(method)
                .setUrl(API_ENDPOINT + path)
                .setFollowRedirects(true);
        if (lastSync!=null) {
            String lastSyncHeader = API_FORMAT.format(lastSync);
            Log.d("deck lastSync", lastSyncHeader); 
            //##### output is: Fri, 7 Dec 2018 01:14:37 GMT+01:00

            Map<String, List<String>> header = new HashMap<>();
            List<String> hdr = new ArrayList<>();
            hdr.add(lastSyncHeader);
            header.put("If-Modified-Since", hdr);
            builder.setHeader(header);
        }
        return builder;
    }
```

The header should be as defined here: https://deck.readthedocs.io/en/latest/API/#headers
`If-Modified-Since: Mon, 5 Nov 2018 09:28:00 GMT`

I set up a little man-in-the-middle, this is what i see:
![grafik](https://user-images.githubusercontent.com/6911132/49647263-303df900-fa22-11e8-957d-eab5b766e543.png)

So according to this, the header isn't written. 
Am i missing something?

**Comment by David-Development** [comment]
@desperateCoder Thanks for the report. Just looked into it again and indeed it looks like that the headers are not send (nor processed).. reference: https://github.com/nextcloud/android/blob/b31d650b28fa3819f7076f1d1464369852ed0fb5/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L165

I'll look into it!

**Comment by desperateCoder** [comment]
Great, thanks for your support!

**Comment by David-Development** [comment]
For sure, glad to see that you guys are still using it! And this is how we make this SingleSignOn library even better! :)

Just created a PR in the nextcloud-android repo as it needs to be fixed there. Is it possible for you to test the fix before we merge it? (https://github.com/nextcloud/android/pull/3330). 

I don't have a proper testing-environment here to test if the headers are send properly.

**Comment by desperateCoder** [comment]
It is very convenient to use it, so there is no reason not to... :) Why struggle over self signed certs or that kind of problems?!?

Sure, i can test it, but don't i have to update the SSO-Libs as well? Which version should i include?
My current version is: 

    implementation 'com.github.nextcloud:android-SingleSignOn:0.1.2'

**Comment by David-Development** [comment]
That is very true! :)

> but don't i have to update the SSO-Libs as well

No, no need to update dependencies. Just run/compile the updated nextcloud-files apk and that should do the trick ;-)

**Comment by desperateCoder** [comment]
Like a charm! Look what we got here!

![grafik](https://user-images.githubusercontent.com/6911132/49651791-78fcae80-fa30-11e8-9390-8a47cb200b24.png)

**Comment by David-Development** [comment]
@desperateCoder Yeeay, great 👍 🎉

**Comment by desperateCoder** [comment]
Thanks buddy! It even works! if i set the Date to now, no results are returned by the server. 
Get a Cooke, you deserved one!
