### ISSUE TITLE
Ok/Cancel buttons are invisible on permission dialog

### ISSUE THREAD

**Issue by wzurborg** [nextcloud/Android-SingleSignOn#390]
This is #195 reappearing with SSO 0.5.6 in Nextcloud Notes.
Reference: https://github.com/stefan-niedermann/nextcloud-notes/issues/1357

I am trying to use Nextcloud Notes Version: 3.4.1, which references SSO 0.5.6 and shows this behaviour.

![grafik](https://user-images.githubusercontent.com/1320950/135090745-dfe4aeb0-6bf9-4c29-b1d3-895d42874258.png)

**Comment by stefan-niedermann** [comment]
@wzurborg is this issue still valid? If yes: which version of the Nextcloud (Files) Android app are you using?

**Comment by wzurborg** [comment]
App is now working with versions 3.4.16 (Mobile) and 3.4.11 (Tablet). Thank you!
