### ISSUE TITLE
Provide convenience class for OCS requests

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#401]
# Issue

Each response from `/ocs/…` endpoints is wrapped in a container which contains some meta information:

```json
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
    }
}
```

Object mappers in 3rd party apps currently have to care about this wrapper in each object mapper.

# Proposal

For the [`Notes`](https://github.com/stefan-niedermann/nextcloud-notes/) app, i wrote a little convenience class so i can write my `Retrofit` interface like

```java
@GET("users/{userId}?format=json")
Call<OcsResponse<OcsUser>> getUser(@Path("userId") String userId);
```

Since this wrapper is not app specific but for the Nextcloud core and reusable for each `OCS` api call, i suggest to move the class into the SSO library.
The actual object mappers which are used in 3rd party apps will be way more lightweight and don't to have repeated code.

```java
/**
 * <p>A generic wrapper for <a href="https://www.open-collaboration-services.org/">OpenCollaborationServices</a> calls.</p>
 * <p>This is needed for API endpoints located at <code>/ocs/…</code>. It is usually not used for APIs of 3rd party server apps like <a href="https://deck.readthedocs.io/en/latest/API/">Deck</a> or <a href="https://github.com/nextcloud/notes/blob/master/docs/api/README.md">Notes</a></p>
 *
 * @param <T> defines the payload of this {@link OcsResponse}.
 */
class OcsResponse<T> {
    public OcsWrapper<T> ocs;

    public static class OcsWrapper<T> {
        public OcsMeta meta;
        public T data;
    }

    public static class OcsMeta {
        public String status;
        public int statuscode;
        public String message;
    }
}
```

**Comment by David-Development** [comment]
@stefan-niedermann Sounds like a great idea 👍 Would also make it easier for people to get started if they have some types already available as they start working with SSO.

**Comment by stefan-niedermann** [comment]
@David-Development what do you think is the right package for this class? `model` or `api`? Keeping in mind, that we can later *maybe* extend the helper class with other convenience classes like for users, capabilities etc.

**Comment by tobiasKaminsky** [comment]
Model I think, as api is for defining how api looks like (e.g. create calls) and model is response.
But not 100% sure.

**Comment by stefan-niedermann** [comment]
My first thought was also `Model`, however, there is [`ParsedResponse`](https://github.com/nextcloud/Android-SingleSignOn/blob/master/lib/src/main/java/com/nextcloud/android/sso/api/ParsedResponse.java) in `api`. It does something **similar** but not identical: It allows to get the Headers of the response.

I will go for `model` in a PR, maybe even a subpackage like `model.ocs` where we can define some default mappers for `ocs` requests like `OcsUser` or `OcsCapabilities` next to the generic `OcsResponse` wrapper...
