### ISSUE TITLE
Handle `QueryParam` with key "`c`"

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#414]
# Issue

Given one adds a `QueryParam` with the key `c`, the backend will respond with `HTTP 400` as this parameter is [reserved for CSRF protection](https://github.com/nextcloud/Android-SingleSignOn/issues/266#issuecomment-711643847).

# Options

## Don't handle at all

This leads to a `HTTP 400` response with a [stacktrace that is quite hard to understand](https://github.com/nextcloud/Android-SingleSignOn/issues/266#issue-723006820) (status quo)

## Log warning

If the user actually knows what he does and *wants* to add this parameter, we don't block him but still are visible in case he wonders why something fails.

## Throw meaningful `Exception`

One could assume that it is simply *wrong* to add this parameter and throw a meaningful `Exception`. This is a breaking change and *can* be a potential issue in case the user really *wants* to do this for some reason.

---

Looking forward for opinions :slightly_smiling_face: 
PS.: This issue has been split out of #266

**Comment by tobiasKaminsky** [comment]
Is this not also a problem for a regular http call directly to server, without SSO?

**Comment by stefan-niedermann** [comment]
Yes, it is.
