### ISSUE TITLE
i18n: `Benötigt keine Übersetzung. Für Android wird nur die formelle Übersetzung verwendet (de_DE).`

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#456]
Recently a user contacted me with the following error prompt in the Notes Android app (LineageOS 18.1):

![image](https://user-images.githubusercontent.com/4741199/169645851-a5f7d42f-72ce-4a20-9f65-19680c19c744.png)

Separate from being guilty myself for the failure itself, I was curious about the error message, so I did some research.

There are two german translations: [`de`](https://github.com/nextcloud/Android-SingleSignOn/blob/master/lib/src/main/res/values-de/strings.xml) and [`de-rDE`](https://github.com/nextcloud/Android-SingleSignOn/blob/master/lib/src/main/res/values-de-rDE/strings.xml). While the translations of `de-rDE` look fine, all translations of `de` look quite odd.

Probably one thought, they would not ever appear on the UI, but this seems to be the case.

- Should one dig more into this?
- Should we simply add proper traanslations to the `de` file`?

**Comment by David-Development** [comment]
Hm.. weird. I assume the user is in austria or switzerland? I believe for germany the language code would be `de-rDE`. Since we don't have `de-rCH` the fallback will be `values-de`. At leasts that's what I'm getting from the following explanation on stackoverflow. So we'd only need `values-de` and `values-de-rDE` can and probably should be deleted if we don't plan on having any special translations for Germany / Switzerland / Austria.

> The difference between values-de-rDE and values-de is that the first is referring to the country and language, while the other only requires the language.
>
>What region is chosen can be determined in System Settings. German (Germany) is values-de-rDE while German (Switzerland) is values-de-rCH, but both are values-de.
>
>If the system is set to German (Germany), it will first read all values from values-de-rDE, then the missing values from values-de, and finally from the default values.
>
>This is useful for when values contains American English, and values-en-rGB can provide only the strings that are different (i.e. colour, flavour, customise).

Source: https://stackoverflow.com/a/26415196/13370504

**Comment by stefan-niedermann** [comment]
So what needs to be done to fix this? Just delete the region derivates? Ensure they aren't transferred from transifex in the future?

**Comment by David-Development** [comment]
@stefan-niedermann Exactly. At least that's my understanding 😅 Just keep `values-de` and delete all the other derivates.

**Comment by stefan-niedermann** [comment]
How do we ensure they won't be readded by the next transifex merge?

**Comment by tobiasKaminsky** [comment]
Fix is in https://github.com/nextcloud/docker-ci/pull/472

**Comment by nickvergessen** [comment]
Fixed in https://github.com/nextcloud/Android-SingleSignOn/commit/8b62eba46d90cdb471791795749fcd4729677a26

**Comment by stefan-niedermann** [comment]
Awesome, thanks :)

Guess we can close this issue then?
