### ISSUE TITLE
If only dev app is installed SSO doesn't work

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#470]
If users only have the dev version installed, the SSO connection doesn't work in the notes and news app.

According to the report in the notes app (see ticket below) I assume that it fails in the Token Exchange part - so the call to [authenticateSingleSignAccount](https://github.com/nextcloud/Android-SingleSignOn/blob/fe05d915ca689c590326b9ccdea1618140e0287c/lib/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L336)

Ref:
- https://github.com/stefan-niedermann/nextcloud-notes/issues/1547
- https://github.com/nextcloud/news-android/issues/1033

**Comment by David-Development** [comment]
@stefan-niedermann I figured out why it's not working anymore.. looks like that the dev app uses the production `accountType` ( `nextcloud` instead of `nextcloud.beta`). Therefore when we get the accounts from the Android Account Manager we have no idea where this account came from (dev, qa or beta). Since the dev app is using the same `accountType` as the production app we use the prod `packageId` to start the auth intent. In case the prod app is not installed the request will obviously fail. 

<img width="245" alt="Bildschirm­foto 2022-12-03 um 09 47 56" src="https://user-images.githubusercontent.com/4489723/205432620-5fb1a8f4-029e-436f-8e1f-e8ba1a36150f.png">

@tobiasKaminsky @AlvaroBrey 

After digging through the android files app source code it looks like that the logic on how to select the `accountType` hasn't been changed (last change was from Tobias 5 years ago) ([ref](https://github.com/nextcloud/android/blame/190f5dbbd36ec88d7a83053cdb46f345821f66e0/app/src/main/java/com/owncloud/android/MainApp.java#L636)). However I noticed a few inconsistencies - it looks like the dev resources were moved around inside the app back in march ([ref](https://github.com/nextcloud/android/blob/fbfa7fa746a509be165219d960030cf4a0967eea/app/src/versionDev/res/values/setup.xml)). I believe that the dev variables are **not** applied anymore. I can confirm, that my dev app doesn't have a beta indicator and the name of the app is just "Nextcloud" and not "Nextcloud Dev". I believe that the resources are not bundled in the app anymore - and I believe that the `build.gradle` is missing the resource sets for this flavor..?

I'm not sure where to find the QA apk but I assume that this might be an issue there as well.

**Comment by tobiasKaminsky** [comment]
> . I can confirm, that my dev app doesn't have a beta indicator and the name of the app is just "Nextcloud" and not "Nextcloud Dev".

![image](https://user-images.githubusercontent.com/5836855/205625006-110c30fc-bad1-4e27-b9b8-3c79c2a4a5ab.png)


I build it manually on latest master.

**Comment by tobiasKaminsky** [comment]
Hm.
I tried it and it works for me?

Installed:
- https://download.nextcloud.com/android/dev/nextcloud-dev-20221203.apk
- https://f-droid.org/repo/it.niedermann.nextcloud.deck_1021006.apk

**Comment by David-Development** [comment]
I used https://f-droid.org/packages/com.nextcloud.android.beta/

**Comment by tobiasKaminsky** [comment]
I updated their build receipt, let's see: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12205

**Comment by stefan-niedermann** [comment]
@David-Development this issue can be closed, no?
