### ISSUE TITLE
Implement currentUserChanged listener

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#48]
Currently one is able to `set` a current user and `get` a current user. Internally this is done by setting and reading a SharedPreferences.

We are initializing our `API`-class in Deck by `getting` the current user. For changes we would have to implement some way to reinitialize our `API`. Alternatively the `API`-class can handle this itself by using a `SharedPreferencesListener` - But since we already have those nice methods with setting and getting it would be great if a `SharedPreferencesListener` would be also provided by the SSO (because SSO is the only one who knows the Keys)

What do you think @desperateCoder @tobiasKaminsky @David-Development ?

**Comment by desperateCoder** [comment]
Didn't know there was such kind of listener, but I'd say it's nice to have, but not mandatory. Since we are setting the account ourselves, we know well, when it has changed. The only benefit of the listener would be, that we can stay lazy af :D

**Comment by stefan-niedermann** [comment]
Here is an example implementation i am using in the Notes app to detect the `syncOnlyOnWifi`-option changed: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java#L76-L81

Another benefit is that we are keeping our code cleaner (imho) because we do not have to pass those kind of data through our constructors and method calls.

**Comment by desperateCoder** [comment]
Yeah, as I said, nice to have. Its soo cute how you are trying to hide your lazyness behind "clean code" :-*

**Comment by tobiasKaminsky** [comment]
> because SSO is the only one who knows the Keys

SSO only implements the getter/setter, but the real preferences are stored by the app.
So we could add this snippet, but then your app still needs to register this listener as the library itself cannot do this, or?

**Comment by desperateCoder** [comment]
If I didn't miss something, the whole point of this issue is pointless, right? Since the SSO set-call handles anything we need, why would we need to know the account changed? 

I'd just add a addListener convenience method to the helper class, but I'm not even sure if we need this at all...

**Comment by tobiasKaminsky** [comment]
:-D 
I think this is something you and Stefan needs to talk about ;-)
I am pretty sure you both will sort this out ;-)

**Comment by desperateCoder** [comment]
@tobiasKaminsky WE just talked about this and in fact this would simplify some parts of our code and lead to less account handling boilerplate code. Would be convenient to have a method for listener registration. Would that be much work for you guys? 

We could register the listener by ourselves, but we would have to know the exact keys, so I'd say the SSO lib should handle this.

**Comment by tobiasKaminsky** [comment]
I can do that.
Can we have a chat so that I know what exactly I shall do?

**Comment by tobiasKaminsky** [comment]
https://cloud.nextcloud.com/call/uoqrsatw

**Comment by David-Development** [comment]
This was implemented in #50, right?

**Comment by tobiasKaminsky** [comment]
> This was implemented in #50, right?

Riiiiiiight :-)

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann @desperateCoder if you see any problem, please open up a new issue.

**Comment by AndyScherzinger** [comment]
Jitpack build for master snapshot is completed https://jitpack.io/com/github/nextcloud/Android-SingleSignOn/master-d07456fa3c-1/build.log
