### ISSUE TITLE
Migrate to Material 3 theme

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#494]
Mainly the style of the dialogs has changed - more border radius and so on.

It's not a big deal, but looks quite inconsistent if the 3rd party app *and* the files app have new dialogs, but when importing an account the old dialogs are displayed...

cc @David-Development @AndyScherzinger @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@AlvaroBrey maybe this is a quick thing for you? :crossed_fingers:
