### ISSUE TITLE
add gson as dependency of sso library

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#67]
TODO: also remove import of gson from README after adding gson as a dependency to sso.

**Comment by burningthumb** [comment]
So maybe there is something I don't understand.  I still need to include the dependency:

` implementation 'com.google.code.gson:gson:2.8.5`

In my libraries build.gradle file.  

In fact I took a closer look at the original build.gradle file for the sso library and I see it already did include this dependency (now its in there twice - sorry I did not notice it the first time).

Any ideas ?

**Comment by Unpublished** [comment]
You can try to change `implementation 'com.google.code.gson:gson:2.8.5` to `api 'com.google.code.gson:gson:2.8.5` in SSO.

It should include the gson library transitively.

**Comment by burningthumb** [comment]
Yes I think that is the solution since I am using the SSO library from another library it needs to be api instead implementation.  I've made the change and will add a pull request.
