### ISSUE TITLE
request additional permission for lineageos android 7 devices

### ISSUE THREAD

**Issue by David-Development** [nextcloud/Android-SingleSignOn#68]
Account listing does not work on LineagsOS (Android 7) sometimes.. Probably it's missing the following permission: `android.permission.USE_CREDENTIALS` (https://android.stackexchange.com/questions/38369/what-can-an-app-do-with-the-use-accounts-on-the-device-permission)

Reference: https://github.com/stefan-niedermann/nextcloud-deck/issues/81#issuecomment-510256157

**Comment by tobiasKaminsky** [comment]
Strange, i never had a problem with LineageOS.
He is also saying that he needs to accent "contact" permission…

**Comment by tobiasKaminsky** [comment]
Is this still valid?

**Comment by David-Development** [comment]
Not sure.. let's close it until someone complains that it's not working 😅
