### ISSUE TITLE
Add to jitpack

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/Android-SingleSignOn#7]
Once this is at some decent point this should be published via jitpack, for either access.
Release should be done from official NC team members (I hope this is ok).

**Comment by mario** [comment]
I think @David-Development should definitely have a say in the development and releases. Who does the final "kick" is largely irrelevant, but everyone who contributes is official enough, especially if contribution is THIS significant.

**Comment by tobiasKaminsky** [comment]
Whit #10 jitpack is working, e.g. https://jitpack.io/com/github/Nextcloud/Android-SingleSignOn/buildScript-8068d72f18-1/build.log is compiling.
