### ISSUE TITLE
Prevent exposing password at all

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/Android-SingleSignOn#9]
As discussed with @rullzer, we had the idea to never expose the password at all:

- appX requests access to Nextcloud data from the NextcloudApp
- NC app exchanges some secret with appX to bind it
- NC app requests a new accesstoken for that app (via new endpoint on server side)
- NC app internally binds this access token to the secret it communicated with appX

**Comment by tobiasKaminsky** [comment]
To harden this further, we should also verify the calling package, so that both must match: calling package name and secret token

**Comment by rullzer** [comment]
Also as a reminder to myself. We should extend the server scope. so that if you request a new token for appX. That token can no longer request new tokens.

**Comment by tobiasKaminsky** [comment]
@David-Development this then would mean that we also can avoid to provide server url and password to the 3rd party app, or?

**Comment by tobiasKaminsky** [comment]
Right, passing the server url should still be done, for UX :+1: 
But I would like to remove the password entirely, so that even the freshly generated token is not transferred within android and thus is never exposed.

I will give it a try.

**Comment by tobiasKaminsky** [comment]
Password is indeed not needed, so I will create a PR for this on Monday, based on #8, so that #8 is not cluttered up too much.

**Comment by tobiasKaminsky** [comment]
I would also include calling package as further security step, so that both must match: calling package and token.

**Comment by tobiasKaminsky** [comment]
I have added calling package, but for now we are using the same token as the original login.

**Comment by tobiasKaminsky** [comment]
@rullzer we can then use the passed calling package name to name the auth token, once this is ready.

**Comment by rullzer** [comment]
Yeah something like that should work

**Comment by David-Development** [comment]
I think this is already implemented by now, isn't it? (See https://github.com/nextcloud/android/blob/sso/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java#L182)

**Comment by tobiasKaminsky** [comment]
@David-Development yes, this is implemented :+1:
