### ISSUE TITLE
Document Proguard Requirements

### ISSUE THREAD

**Issue by burningthumb** [nextcloud/Android-SingleSignOn#92]
I have Proguard enabled for release buildTypes in my `build.gradle` file:

```
buildTypes
     {
          release 
          {
               minifyEnabled true
               proguardFiles getDefaultProguardFile('proguard-android.txt'), 
                                       'proguard-rules.pro'
          }
     }

```
And I could not sign in when I built a signed .apk.

I know very little about Proguard and **really have no idea how it works**.  What I did do is google it and I found a similar issue in the Nextcloud App project.

So I added these lines to my `proguard-rules.pro` file and while it does now work using these rules, and I can sign in with a release build, it would be great if someone who understands Proguard could document exactly what the requirements are for SingleSignOn in the README.md file:

```
-keep class com.nextcloud.android.sso.** { *; }
-keep,allowshrinking class com.owncloud.android.** { *; }
-keep,allowshrinking class org.apache.jackrabbit.webdav.** { *; }
-keep,allowshrinking class org.apache.commons.codec.** { *; }
-keep,allowshrinking class org.apache.commons.logging.** { *; }
-keep,allowshrinking class org.parceler.** { *; }
-keep,allowshrinking class org.slf4j.** { *; }
```

**Comment by tobiasKaminsky** [comment]
We do not use proguard at all, so I also do not have any knowledge about it.
As it is also not needed for SSO/NC at all, documentating it here might make user think that they have to use it and we have to maintain the documentation.

So I am fine, that it is explained in an issue here, but as it is not required, we will not do an official documentation for it.
