### ISSUE TITLE
Include a Logging-Interceptor

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/Android-SingleSignOn#95]
Hello friends!

As I already pitched, here is an issue for implementing a convenient way of seeing how the HTTP-Request looks like in the end at dev-time.

The implementation should be not much effort, see [this](https://stackoverflow.com/questions/32514410/logging-with-retrofit-2).

Please also update the README describing how to use this feature.

I'd love to have this for the future, since i am struggeling on this again right now.

Greetings! See you at NC Conference!

**Comment by stefan-niedermann** [comment]
Has this issue been fixed with https://github.com/nextcloud/Android-SingleSignOn/pull/105 ?

**Comment by tobiasKaminsky** [comment]
Yes, at least Arthur said it is enough.

**Comment by desperateCoder** [comment]
It is! Thank you!! ❤️
